# -*- coding: utf-8 -*-
"""login time analyze.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13spo8Cc-yjNuP526DUbJ_q10ZkNTgrc1
"""

import pymongo
import pandas as pd
import numpy as np
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore') # 加上這行只是把下面的一些加上這行只是把下面的一些warning性質的輸出都省略掉

client = pymongo.MongoClient("xxxxxxxxxxxxxx")
db = client["xxxxxxxxxxx"]
collist = db.list_collection_names()
print(collist)

from google.colab import drive
drive.mount('/content/gdrive') # 此處需要登入 google 帳號

def label_login(value):
    if value == 5:
        value='L0'
        return value
    elif value == 4:
        value='L1'
        return value
    # else:
    #   value = 'Llobby'

login_df = pd.DataFrame(data=db["login_log"].find({"accountid": 890649},{'_id':0,'event_code':1,'createtime':1}).sort([("createtime", 1)]))

login_df

login4 = login_df[login_df['event_code'] == 4]

login4['createtime'] = pd.to_datetime(login4['createtime'])

login4['createtime']

login4["weekday"] = login4["createtime"].apply(lambda x: x.weekday())

login4["hour"] = login4["createtime"].apply(lambda x: x.hour)

login4

x = login4["weekday"]
y = login4["hour"]

login4

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

f, ax = plt.subplots(figsize=(15, 15))
sns.scatterplot(x=x, y=y, s=1, color=".15")
sns.histplot(x=x, y=y, bins=500, pthresh=.1, cmap="mako")
sns.kdeplot(x=x, y=y, levels=10, color="b", linewidths=30, fill=True, joint_kws={'alpha': 0.9})

plt.xlabel('weekday', fontsize=30)
plt.ylabel('hour', fontsize=30)
plt.ylim(0, 24) 
plt.xlim(0, 7) 

plt.xticks(fontsize=25)
plt.yticks(fontsize=25)

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

f, ax = plt.subplots(figsize=(15, 15))
sns.scatterplot(x=x, y=y, s=1, color=".15")
sns.histplot(x=x, y=y, bins=500, pthresh=.1, cmap="mako")
sns.kdeplot(x=x, y=y, levels=10, color="b", linewidths=30, fill=True, joint_kws={'alpha': 0.9})

plt.xlabel('weekday', fontsize=30)
plt.ylabel('hour', fontsize=30)
plt.ylim(0, 24) 
plt.xlim(0, 7) 

plt.xticks(fontsize=25)
plt.yticks(fontsize=25)

